development:
  adapter: postgresql
  database: sample_app_dev
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: sample_app_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sample_app
  pool: 5
  timeout: 5000
